// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using order_routing.Server.Data;

#nullable disable

namespace order_routing.Server.Migrations
{
    [DbContext(typeof(OrderDbContext))]
    [Migration("20260623180547_AddedMockUsers")]
    partial class AddedMockUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("order_routing.Server.Models.OrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<DateOnly>("CreationDate")
                        .HasColumnType("date");

                    b.Property<int>("OrderLineStatus")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("StoreId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("StoreId");

                    b.ToTable("OrderLines");
                });

            modelBuilder.Entity("order_routing.Server.Models.OrderLineFulfillment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("CreationDate")
                        .HasColumnType("date");

                    b.Property<bool>("FirstVerification")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderLineId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<bool>("SecondVerification")
                        .HasColumnType("boolean");

                    b.Property<int>("StoreId")
                        .HasColumnType("integer");

                    b.Property<int>("fulfillmentTransportMethod")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderLineId");

                    b.HasIndex("StoreId");

                    b.ToTable("OrderLineFullfillments");
                });

            modelBuilder.Entity("order_routing.Server.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Item 1",
                            ProductCode = "ITEM001"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Item 2",
                            ProductCode = "ITEM002"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Item 3",
                            ProductCode = "ITEM003"
                        });
                });

            modelBuilder.Entity("order_routing.Server.Models.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StoreDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Address 1",
                            PhoneNumber = "2101234567",
                            StoreDescription = "Store 1"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Address 2",
                            PhoneNumber = "2104501929",
                            StoreDescription = "Store 2"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Address 3",
                            PhoneNumber = "2106316478",
                            StoreDescription = "Store 3"
                        });
                });

            modelBuilder.Entity("order_routing.Server.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("StoreId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "$2a$11$hdK6GmVpIihFMTAwigXL0Ov4Q5fuE3uayVlHgbEeQn7ZNkEjCDrfy",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            PasswordHash = "$2a$11$4vkFvLlv66iIotzFskanX.PNIYozDrGmxRYpS9Cg/EQnI0PfOIUYq",
                            Role = "StoreUser",
                            StoreId = 1,
                            Username = "store1"
                        });
                });

            modelBuilder.Entity("order_routing.Server.Models.OrderLine", b =>
                {
                    b.HasOne("order_routing.Server.Models.Product", "Product")
                        .WithMany("OrderLines")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("order_routing.Server.Models.Store", "Store")
                        .WithMany("OrderLines")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("order_routing.Server.Models.OrderLineFulfillment", b =>
                {
                    b.HasOne("order_routing.Server.Models.OrderLine", "OrderLine")
                        .WithMany("OrderLineFulfillment")
                        .HasForeignKey("OrderLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("order_routing.Server.Models.Store", "Store")
                        .WithMany("OrderLineFulfillments")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrderLine");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("order_routing.Server.Models.User", b =>
                {
                    b.HasOne("order_routing.Server.Models.Store", "Store")
                        .WithMany("Users")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Store");
                });

            modelBuilder.Entity("order_routing.Server.Models.OrderLine", b =>
                {
                    b.Navigation("OrderLineFulfillment");
                });

            modelBuilder.Entity("order_routing.Server.Models.Product", b =>
                {
                    b.Navigation("OrderLines");
                });

            modelBuilder.Entity("order_routing.Server.Models.Store", b =>
                {
                    b.Navigation("OrderLineFulfillments");

                    b.Navigation("OrderLines");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
